Feature/#63 ソースファイルから読み込み
cafecoder-dev/cafecoder-front pull request #65
Opened 2021-11-22 16:00 UTC by earlgray283

2021-11-22 23:28 UTC, kichi2004 requested changes

2021-11-22 23:28 UTC, kichi2004 commented on app/components/ViewProblemCard.vue
> +  change(file: File) {
`change` ではなくもう少し具体的な名前にしてほしい

2021-11-23 08:33 UTC, earlgray283 commented on app/components/ViewProblemCard.vue
> +  change(file: File) {
`onFileInputChange` に変更した

2021-11-23 10:27 UTC, kichi2004 approved these changes

2021-11-23 15:32 UTC, earlgray283 commented
merge します

2021-11-23 15:32 UTC, merged